"""initial_schema

Revision ID: fb49234a3601
Revises: 
Create Date: 2026-10-04 10:27:31.503878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb49234a3601'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('admin_username', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('boarding_centers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('daily_rate_toman', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boarding_centers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boarding_centers_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_boarding_centers_slug'), ['slug'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title_fa', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('clinics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('is_emergency_24h', sa.Boolean(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinics_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinics_slug'), ['slug'], unique=True)

    op.create_table('coupons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('coupon_type', sa.Enum('PERCENTAGE', 'FIXED', name='coupontype'), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('max_discount_cap_tomans', sa.Integer(), nullable=True),
    sa.Column('min_order_amount_tomans', sa.Integer(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=False),
    sa.Column('remaining_usage', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_code'), ['code'], unique=True)

    op.create_table('otp_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_verifications_phone_number'), ['phone_number'], unique=False)

    op.create_table('platform_feature_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False),
    sa.Column('name_fa', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_feature_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_feature_flags_module_key'), ['module_key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('CUSTOMER', 'PET_PARENT', 'SELLER', 'ADMIN', 'VETERINARIAN', 'EVENT_ORGANIZER', 'TRAINER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)

    op.create_table('admin_password_resets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('reset_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_password_resets_reset_token_hash'), ['reset_token_hash'], unique=True)

    op.create_table('admin_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_sessions_session_token_hash'), ['session_token_hash'], unique=True)

    op.create_table('adoption_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('publisher_id', sa.String(length=36), nullable=False),
    sa.Column('pet_name', sa.String(length=50), nullable=False),
    sa.Column('species', sa.Enum('DOG', 'CAT', 'BIRD', 'SMALL_PET', 'OTHER', name='petspecies'), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'UNKNOWN', name='petsex'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('health_status', sa.String(length=200), nullable=False),
    sa.Column('vaccination_status', sa.String(length=200), nullable=False),
    sa.Column('is_neutered', sa.Boolean(), nullable=False),
    sa.Column('adoption_fee_tomans', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'UNDER_REVIEW', 'ADOPTED', 'CANCELLED', name='adoptionstatus'), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adoption_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adoption_listings_publisher_id'), ['publisher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adoption_listings_species'), ['species'], unique=False)
        batch_op.create_index(batch_op.f('ix_adoption_listings_status'), ['status'], unique=False)

    op.create_table('canonical_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('title_fa', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('target_species', sa.Enum('DOG', 'CAT', 'BIRD', 'SMALL_PET', 'OTHER', name='petspecies'), nullable=False),
    sa.Column('description_fa', sa.Text(), nullable=True),
    sa.Column('short_description_fa', sa.Text(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('package_weight_grams', sa.Integer(), nullable=True),
    sa.Column('price_tomans', sa.Integer(), nullable=True),
    sa.Column('old_price_tomans', sa.Integer(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('flavor', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('life_stage', sa.String(length=50), nullable=True),
    sa.Column('health_tags', sa.String(length=255), nullable=True),
    sa.Column('primary_image_url', sa.String(length=500), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('seo_keywords', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canonical_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canonical_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_products_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_products_slug'), ['slug'], unique=True)

    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_time', sa.String(length=50), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price_tomans', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('registered_count', sa.Integer(), nullable=False),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.Column('organizer_id', sa.String(length=36), nullable=False),
    sa.Column('moderation_status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', name='eventmoderationstatus'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_moderation_status'), ['moderation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_organizer_id'), ['organizer_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PAYMENT_PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('fulfillment_stage', sa.Enum('CONFIRMED', 'COLLECTING_ITEMS', 'PACKAGING', 'SENDING', 'HANDED_TO_COURIER', 'DELIVERED', name='fulfillmentstage'), nullable=False),
    sa.Column('total_amount_tomans', sa.Integer(), nullable=False),
    sa.Column('discount_amount_tomans', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('calculated_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('shipping_timeslot', sa.String(length=100), nullable=True),
    sa.Column('payment_authority', sa.String(length=100), nullable=True),
    sa.Column('payment_ref_id', sa.String(length=100), nullable=True),
    sa.Column('stage_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_packaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_sending_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_courier_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('paw_points_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paw_points_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paw_points_ledger_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_paw_points_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('pets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('species', sa.Enum('DOG', 'CAT', 'BIRD', 'SMALL_PET', 'OTHER', name='petspecies'), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'UNKNOWN', name='petsex'), nullable=False),
    sa.Column('birth_date', sa.String(length=20), nullable=True),
    sa.Column('estimated_age_months', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('microchip_number', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('vaccination_status', sa.String(length=100), nullable=True),
    sa.Column('vaccination_reminders', sa.Text(), nullable=True),
    sa.Column('passport_doc_url', sa.String(length=500), nullable=True),
    sa.Column('passport_doc_verified', sa.Boolean(), nullable=False),
    sa.Column('is_neutered', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('qr_passport_token', sa.String(length=64), nullable=False),
    sa.Column('is_lost', sa.Boolean(), nullable=False),
    sa.Column('lost_alert_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pets_qr_passport_token'), ['qr_passport_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_pets_user_id'), ['user_id'], unique=False)

    op.create_table('sellers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('store_name_fa', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=False),
    sa.Column('sheba_number', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sellers_slug'), ['slug'], unique=True)

    op.create_table('trainers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('speciality', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('hourly_rate_toman', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('blocked_dates', sa.JSON(), nullable=False),
    sa.Column('available_days', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainers_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_trainers_user_id'), ['user_id'], unique=True)

    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veterinarians',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('medical_license_number', sa.String(length=50), nullable=False),
    sa.Column('speciality', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('consultation_fee_toman', sa.Integer(), nullable=False),
    sa.Column('blocked_dates', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medical_license_number')
    )
    with op.batch_alter_table('veterinarians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veterinarians_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('wallet_withdrawal_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount_tomans', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=30), nullable=False),
    sa.Column('sheba_number', sa.String(length=34), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'PROCESSING', 'PAID', 'REJECTED', name='withdrawalstatus'), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_withdrawal_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_withdrawal_requests_user_id'), ['user_id'], unique=False)

    op.create_table('wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('balance_tomans', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_user_id'), ['user_id'], unique=True)

    op.create_table('adoption_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('applicant_id', sa.String(length=36), nullable=False),
    sa.Column('applicant_name', sa.String(length=100), nullable=False),
    sa.Column('applicant_phone', sa.String(length=20), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('has_other_pets', sa.Boolean(), nullable=False),
    sa.Column('housing_type', sa.String(length=100), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['adoption_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adoption_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adoption_applications_applicant_id'), ['applicant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adoption_applications_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adoption_applications_status'), ['status'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('vet_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_date', sa.String(length=20), nullable=False),
    sa.Column('timeslot', sa.String(length=30), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointmentstatus'), nullable=False),
    sa.Column('reason_for_visit', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('treatment_summary', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('treatment_performed', sa.Text(), nullable=True),
    sa.Column('next_visit_needed', sa.Boolean(), nullable=False),
    sa.Column('recommended_next_visit', sa.String(length=50), nullable=True),
    sa.Column('reminder_required', sa.Boolean(), nullable=False),
    sa.Column('total_fee_toman', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('cancellation_fee_toman', sa.Integer(), nullable=False),
    sa.Column('refund_amount_toman', sa.Integer(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_id'], ['veterinarians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_pet_id'), ['pet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_vet_id'), ['vet_id'], unique=False)

    op.create_table('boarding_bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('check_in_date', sa.String(length=20), nullable=False),
    sa.Column('check_out_date', sa.String(length=20), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('total_fee_toman', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', name='boardingbookingstatus'), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['boarding_centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boarding_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boarding_bookings_center_id'), ['center_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_boarding_bookings_pet_id'), ['pet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_boarding_bookings_user_id'), ['user_id'], unique=False)

    op.create_table('care_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('species', sa.Enum('DOG', 'CAT', 'BIRD', 'SMALL_PET', 'OTHER', name='petspecies'), nullable=False),
    sa.Column('category', sa.Enum('WALK', 'FOOD', 'MEDICATION', 'HYGIENE', 'WATER', name='taskcategory'), nullable=False),
    sa.Column('target_metric', sa.String(length=50), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=True),
    sa.Column('scheduled_time', sa.String(length=10), nullable=True),
    sa.Column('scheduled_date', sa.String(length=20), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('creator_role', sa.String(length=50), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('care_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_care_tasks_pet_id'), ['pet_id'], unique=False)

    op.create_table('coupon_redemptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coupon_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('discount_amount_tomans', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'BURNED', 'RELEASED', name='redemptionstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('burned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupon_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_coupon_id'), ['coupon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_user_id'), ['user_id'], unique=False)

    op.create_table('courier_shipments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('courier_name', sa.String(length=100), nullable=False),
    sa.Column('courier_phone', sa.String(length=20), nullable=False),
    sa.Column('tehran_district', sa.Integer(), nullable=False),
    sa.Column('delivery_tier', sa.Enum('STANDARD', 'EXPRESS_3H', name='deliverytier'), nullable=False),
    sa.Column('status', sa.Enum('COURIER_ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'FAILED', name='courierstatus'), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=False),
    sa.Column('current_lng', sa.Float(), nullable=False),
    sa.Column('estimated_delivery_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courier_shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courier_shipments_order_id'), ['order_id'], unique=True)

    op.create_table('event_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_code', sa.String(length=50), nullable=False),
    sa.Column('attendee_name', sa.String(length=150), nullable=False),
    sa.Column('attendee_phone', sa.String(length=30), nullable=False),
    sa.Column('price_paid_tomans', sa.Integer(), nullable=False),
    sa.Column('payment_ref', sa.String(length=100), nullable=True),
    sa.Column('is_checked_in', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qr_code_data', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_tickets_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_tickets_ticket_code'), ['ticket_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_tickets_user_id'), ['user_id'], unique=False)

    op.create_table('lost_pet_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('reporter_user_id', sa.String(length=36), nullable=False),
    sa.Column('last_seen_latitude', sa.Float(), nullable=False),
    sa.Column('last_seen_longitude', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('district', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'CANCELLED', name='alertstatus'), nullable=False),
    sa.Column('broadcast_recipient_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lost_pet_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lost_pet_alerts_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_lost_pet_alerts_pet_id'), ['pet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lost_pet_alerts_reporter_user_id'), ['reporter_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lost_pet_alerts_status'), ['status'], unique=False)

    op.create_table('paw_discount_vouchers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('discount_tomans', sa.Integer(), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('is_redeemed', sa.Boolean(), nullable=False),
    sa.Column('redeemed_order_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['redeemed_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paw_discount_vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paw_discount_vouchers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_paw_discount_vouchers_user_id'), ['user_id'], unique=False)

    op.create_table('pet_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_source', sa.Enum('OWNER', 'VET', 'OTHER', name='activitysource'), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('activity_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_activities_activity_date'), ['activity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_activities_activity_source'), ['activity_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_activities_pet_id'), ['pet_id'], unique=False)

    op.create_table('pet_food_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('product_title_fa', sa.String(length=255), nullable=False),
    sa.Column('weight_variant_text', sa.String(length=50), nullable=False),
    sa.Column('package_weight_kg', sa.Float(), nullable=False),
    sa.Column('daily_consumption_grams', sa.Float(), nullable=False),
    sa.Column('unit_price_toman', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('EVERY_2_WEEKS', 'MONTHLY', 'EVERY_2_MONTHS', name='subscriptionfrequency'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('next_delivery_date', sa.String(length=20), nullable=False),
    sa.Column('delivery_address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_food_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_food_subscriptions_pet_id'), ['pet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_food_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('pet_health_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('dietary_preferences', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('health_book_image_url', sa.String(length=255), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('daily_food_grams', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id')
    )
    op.create_table('product_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    op.create_table('product_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('moderation_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_reviews_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('product_variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('title_fa', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('price_tomans', sa.Integer(), nullable=False),
    sa.Column('old_price_tomans', sa.Integer(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_sku'), ['sku'], unique=False)

    op.create_table('reorder_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('package_weight_grams', sa.Integer(), nullable=False),
    sa.Column('daily_consumption_grams', sa.Integer(), nullable=False),
    sa.Column('depletion_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prompt_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sms_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('price_tomans', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seller_offers', schema=None) as batch_op:
        batch_op.create_index('idx_offers_buybox', ['product_id', 'is_active', 'stock_quantity', 'price_tomans'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_offers_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_offers_seller_id'), ['seller_id'], unique=False)

    op.create_table('smart_collar_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hardware_uid', sa.String(length=50), nullable=False),
    sa.Column('hardware_token', sa.String(length=64), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smart_collar_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smart_collar_tags_hardware_token'), ['hardware_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_smart_collar_tags_hardware_uid'), ['hardware_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_smart_collar_tags_pet_id'), ['pet_id'], unique=False)

    op.create_table('trainer_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trainer_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('session_date', sa.String(length=20), nullable=False),
    sa.Column('timeslot', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='trainersessionstatus'), nullable=False),
    sa.Column('fee_toman', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=100), nullable=True),
    sa.Column('what_was_taught', sa.Text(), nullable=True),
    sa.Column('session_notes_owner_safe', sa.Text(), nullable=True),
    sa.Column('homework_exercises', sa.Text(), nullable=True),
    sa.Column('internal_private_notes', sa.Text(), nullable=True),
    sa.Column('recommended_next_session_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trainer_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainer_sessions_pet_id'), ['pet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trainer_sessions_trainer_id'), ['trainer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trainer_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('vendor_settlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('gross_sales_toman', sa.Integer(), nullable=False),
    sa.Column('platform_commission_toman', sa.Integer(), nullable=False),
    sa.Column('tax_withholding_toman', sa.Integer(), nullable=False),
    sa.Column('net_payout_toman', sa.Integer(), nullable=False),
    sa.Column('iban_sheba', sa.String(length=30), nullable=False),
    sa.Column('paya_reference_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('CALCULATED', 'PAYA_SUBMITTED', 'SETTLED', name='settlementstatus'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paya_reference_id')
    )
    with op.batch_alter_table('vendor_settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_settlements_seller_id'), ['seller_id'], unique=False)

    op.create_table('wallet_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('amount_tomans', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('CREDIT_REFUND', 'CREDIT_DEPOSIT', 'DEBIT_PURCHASE', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_transactions_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('inventory_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('offer_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['seller_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_reservations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_reservations_offer_id'), ['offer_id'], unique=False)

    op.create_table('medical_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('vet_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('prescriptions', sa.JSON(), nullable=False),
    sa.Column('vaccine_administered', sa.String(length=100), nullable=True),
    sa.Column('vaccine_next_due_date', sa.String(length=20), nullable=True),
    sa.Column('allergies_noted', sa.String(length=255), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('vet_signature_license', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_id'], ['veterinarians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_records_pet_id'), ['pet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_vet_id'), ['vet_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('offer_id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=True),
    sa.Column('product_title', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_tomans', sa.Integer(), nullable=False),
    sa.Column('commission_tomans', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_collected', sa.Boolean(), nullable=False),
    sa.Column('is_packaged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['seller_offers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_seller_id'), ['seller_id'], unique=False)

    op.create_table('task_completions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('achieved_value', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['care_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_completions_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_completions_task_id'))

    op.drop_table('task_completions')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_seller_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_records_vet_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_pet_id'))

    op.drop_table('medical_records')
    with op.batch_alter_table('inventory_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_reservations_offer_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_reservations_expires_at'))

    op.drop_table('inventory_reservations')
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_wallet_id'))

    op.drop_table('wallet_transactions')
    with op.batch_alter_table('vendor_settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_settlements_seller_id'))

    op.drop_table('vendor_settlements')
    with op.batch_alter_table('trainer_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainer_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_trainer_sessions_trainer_id'))
        batch_op.drop_index(batch_op.f('ix_trainer_sessions_pet_id'))

    op.drop_table('trainer_sessions')
    with op.batch_alter_table('smart_collar_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smart_collar_tags_pet_id'))
        batch_op.drop_index(batch_op.f('ix_smart_collar_tags_hardware_uid'))
        batch_op.drop_index(batch_op.f('ix_smart_collar_tags_hardware_token'))

    op.drop_table('smart_collar_tags')
    with op.batch_alter_table('seller_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seller_offers_seller_id'))
        batch_op.drop_index(batch_op.f('ix_seller_offers_product_id'))
        batch_op.drop_index('idx_offers_buybox')

    op.drop_table('seller_offers')
    op.drop_table('reorder_schedules')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_sku'))
        batch_op.drop_index(batch_op.f('ix_product_variants_product_id'))

    op.drop_table('product_variants')
    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_product_reviews_product_id'))

    op.drop_table('product_reviews')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    op.drop_table('pet_health_profiles')
    with op.batch_alter_table('pet_food_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_food_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_pet_food_subscriptions_pet_id'))

    op.drop_table('pet_food_subscriptions')
    with op.batch_alter_table('pet_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_activities_pet_id'))
        batch_op.drop_index(batch_op.f('ix_pet_activities_activity_source'))
        batch_op.drop_index(batch_op.f('ix_pet_activities_activity_date'))

    op.drop_table('pet_activities')
    with op.batch_alter_table('paw_discount_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paw_discount_vouchers_user_id'))
        batch_op.drop_index(batch_op.f('ix_paw_discount_vouchers_code'))

    op.drop_table('paw_discount_vouchers')
    with op.batch_alter_table('lost_pet_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lost_pet_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_lost_pet_alerts_reporter_user_id'))
        batch_op.drop_index(batch_op.f('ix_lost_pet_alerts_pet_id'))
        batch_op.drop_index(batch_op.f('ix_lost_pet_alerts_district'))

    op.drop_table('lost_pet_alerts')
    with op.batch_alter_table('event_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_tickets_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_tickets_ticket_code'))
        batch_op.drop_index(batch_op.f('ix_event_tickets_event_id'))

    op.drop_table('event_tickets')
    with op.batch_alter_table('courier_shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courier_shipments_order_id'))

    op.drop_table('courier_shipments')
    with op.batch_alter_table('coupon_redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_order_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_coupon_id'))

    op.drop_table('coupon_redemptions')
    with op.batch_alter_table('care_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_tasks_pet_id'))

    op.drop_table('care_tasks')
    with op.batch_alter_table('boarding_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boarding_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_boarding_bookings_pet_id'))
        batch_op.drop_index(batch_op.f('ix_boarding_bookings_center_id'))

    op.drop_table('boarding_bookings')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_vet_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_user_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_pet_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_clinic_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('adoption_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adoption_applications_status'))
        batch_op.drop_index(batch_op.f('ix_adoption_applications_listing_id'))
        batch_op.drop_index(batch_op.f('ix_adoption_applications_applicant_id'))

    op.drop_table('adoption_applications')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_user_id'))

    op.drop_table('wallets')
    with op.batch_alter_table('wallet_withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_withdrawal_requests_user_id'))

    op.drop_table('wallet_withdrawal_requests')
    with op.batch_alter_table('veterinarians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veterinarians_clinic_id'))

    op.drop_table('veterinarians')
    op.drop_table('user_sessions')
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainers_user_id'))
        batch_op.drop_index(batch_op.f('ix_trainers_city'))

    op.drop_table('trainers')
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sellers_slug'))

    op.drop_table('sellers')
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pets_user_id'))
        batch_op.drop_index(batch_op.f('ix_pets_qr_passport_token'))

    op.drop_table('pets')
    with op.batch_alter_table('paw_points_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paw_points_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_paw_points_ledger_idempotency_key'))

    op.drop_table('paw_points_ledger')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))

    op.drop_table('orders')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_organizer_id'))
        batch_op.drop_index(batch_op.f('ix_events_moderation_status'))
        batch_op.drop_index(batch_op.f('ix_events_city'))

    op.drop_table('events')
    with op.batch_alter_table('canonical_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canonical_products_slug'))
        batch_op.drop_index(batch_op.f('ix_canonical_products_sku'))
        batch_op.drop_index(batch_op.f('ix_canonical_products_brand'))

    op.drop_table('canonical_products')
    with op.batch_alter_table('adoption_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adoption_listings_status'))
        batch_op.drop_index(batch_op.f('ix_adoption_listings_species'))
        batch_op.drop_index(batch_op.f('ix_adoption_listings_publisher_id'))

    op.drop_table('adoption_listings')
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_sessions_session_token_hash'))

    op.drop_table('admin_sessions')
    with op.batch_alter_table('admin_password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_password_resets_reset_token_hash'))

    op.drop_table('admin_password_resets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))

    op.drop_table('users')
    with op.batch_alter_table('platform_feature_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_feature_flags_module_key'))

    op.drop_table('platform_feature_flags')
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_verifications_phone_number'))

    op.drop_table('otp_verifications')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_code'))

    op.drop_table('coupons')
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinics_slug'))
        batch_op.drop_index(batch_op.f('ix_clinics_district'))

    op.drop_table('clinics')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))

    op.drop_table('categories')
    with op.batch_alter_table('boarding_centers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boarding_centers_slug'))
        batch_op.drop_index(batch_op.f('ix_boarding_centers_city'))

    op.drop_table('boarding_centers')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_action'))

    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
